// let arr = [
//     {
//         label: '游戏', value: 2, children: [
//             { label: ' 休闲益智 ', value: 15, label: "休闲     ", value: 10043 },
//             { label: ' 休闲益智 ', value: 15, label: "益智     ", value: 10044 },
//             { label: ' 休闲益智 ', value: 15, label: "消除     ", value: 10046 },
//             { label: ' 休闲益智 ', value: 15, label: "音乐节奏   ", value: 10047 },
//             { label: ' 休闲益智 ', value: 15, label: "解谜     ", value: 10048 },
//             { label: ' 休闲益智 ', value: 15, label: "IO     ", value: 10113 },

//             { label: ' 经营策略 ', value: 16, label: "塔防     ", value: 10062 },
//             { label: ' 经营策略 ', value: 16, label: "古代谋略   ", value: 10122 },
//             { label: ' 经营策略 ', value: 16, label: "现代战略   ", value: 10123 },
//             { label: ' 经营策略 ', value: 16, label: "经营     ", value: 10063 },
//             { label: ' 经营策略 ', value: 16, label: "养成     ", value: 10064 },
//             { label: ' 经营策略 ', value: 16, label: "MOBA   ", value: 10065 },

//             { label: ' 动作射击 ', value: 18, label: "格斗     ", value: 10053 },
//             { label: ' 动作射击 ', value: 18, label: "跑酷     ", value: 10054 },
//             { label: ' 动作射击 ', value: 18, label: "射击     ", value: 10055 },
//             { label: ' 动作射击 ', value: 18, label: "打飞机    ", value: 10056 },

//             { label: ' 角色扮演 ', value: 20, label: "仙侠     ", value: 10118 },
//             { label: ' 角色扮演 ', value: 20, label: "传奇     ", value: 10120 },
//             { label: ' 角色扮演 ', value: 20, label: "魔幻     ", value: 10121 },
//             { label: ' 角色扮演 ', value: 20, label: "武侠     ", value: 10119 },
//             { label: ' 角色扮演 ', value: 20, label: "冒险     ", value: 10057 },
//             { label: ' 角色扮演 ', value: 20, label: "动作     ", value: 10058 },
//             { label: ' 角色扮演 ', value: 20, label: "回合制    ", value: 10059 },
//             { label: ' 角色扮演 ', value: 20, label: "多人在线   ", value: 10060 },
//             { label: ' 角色扮演 ', value: 20, label: "卡牌     ", value: 10061 },
//             { label: ' 角色扮演 ', value: 20, label: "生存     ", value: 10114 },
//             { label: ' 角色扮演 ', value: 20, label: "放置挂机   ", value: 10115 },

//             { label: ' 棋牌桌游 ', value: 21, label: "斗地主    ", value: 10108 },
//             { label: ' 棋牌桌游 ', value: 21, label: "麻将     ", value: 10109 },
//             { label: ' 棋牌桌游 ', value: 21, label: "桌游与棋类  ", value: 10110 },
//             { label: ' 棋牌桌游 ', value: 21, label: "纸牌     ", value: 10111 },
//             { label: ' 棋牌桌游 ', value: 21, label: "捕鱼     ", value: 10500 },
//             { label: ' 体育竞速 ', value: 22, label: "赛车     ", value: 10049 },
//             { label: ' 体育竞速 ', value: 22, label: "篮球     ", value: 10050 },
//             { label: ' 体育竞速 ', value: 22, label: "足球     ", value: 10051 },
//             { label: ' 体育竞速 ', value: 22, label: "运动     ", value: 10052 },
//         ],

// { label: '应用', value: 13, label: ' 影音娱乐 ', value: 23, label: "音乐     ", value: 10066 },
//     { label: '应用', value: 13, label: ' 影音娱乐 ', value: 23, label: "视频     ", value: 10067 },
//     { label: '应用', value: 13, label: ' 影音娱乐 ', value: 23, label: "电视     ", value: 10068 },
//     { label: '应用', value: 13, label: ' 影音娱乐 ', value: 23, label: "电台     ", value: 10069 },
//     { label: '应用', value: 13, label: ' 影音娱乐 ', value: 23, label: "K歌     ", value: 10070 },
//     { label: '应用', value: 13, label: ' 影音娱乐 ', value: 23, label: "直播     ", value: 10071 },
//     { label: '应用', value: 13, label: ' 实用工具 ', value: 24, label: "浏览器    ", value: 10019 },
//     { label: '应用', value: 13, label: ' 实用工具 ', value: 24, label: "输入法    ", value: 10020 },
//     { label: '应用', value: 13, label: ' 实用工具 ', value: 24, label: "Wi-Fi  ", value: 10021 },
//     { label: '应用', value: 13, label: ' 实用工具 ', value: 24, label: "工具     ", value: 10022 },
//     { label: '应用', value: 13, label: ' 实用工具 ', value: 24, label: "闹钟     ", value: 10023 },
//     { label: '应用', value: 13, label: ' 实用工具 ', value: 24, label: "安全性能   ", value: 10024 },
//     { label: '应用', value: 13, label: ' 金融理财 ', value: 25, label: "银行     ", value: 10034 },
//     { label: '应用', value: 13, label: ' 金融理财 ', value: 25, label: "股票基金   ", value: 10035 },
//     { label: '应用', value: 13, label: ' 金融理财 ', value: 25, label: "理财     ", value: 10036 },
//     { label: '应用', value: 13, label: ' 金融理财 ', value: 25, label: "记账     ", value: 10037 },
//     { label: '应用', value: 13, label: ' 金融理财 ', value: 25, label: "彩票     ", value: 10038 },
//     { label: '应用', value: 13, label: ' 金融理财 ', value: 25, label: "贷款     ", value: 10112 },
//     { label: '应用', value: 13, label: ' 社交通讯 ', value: 26, label: "聊天     ", value: 10039 },
//     { label: '应用', value: 13, label: ' 社交通讯 ', value: 26, label: "社区     ", value: 10040 },
//     { label: '应用', value: 13, label: ' 社交通讯 ', value: 26, label: "通讯     ", value: 10041 },
//     { label: '应用', value: 13, label: ' 社交通讯 ', value: 26, label: "婚恋     ", value: 10042 },
//     { label: '应用', value: 13, label: ' 便捷生活 ', value: 27, label: "家政     ", value: 10079 },
//     { label: '应用', value: 13, label: ' 便捷生活 ', value: 27, label: "本地生活   ", value: 10080 },
//     { label: '应用', value: 13, label: ' 便捷生活 ', value: 27, label: "租房买房   ", value: 10081 },
//     { label: '应用', value: 13, label: ' 便捷生活 ', value: 27, label: "家居装修   ", value: 10082 },
//     { label: '应用', value: 13, label: ' 便捷生活 ', value: 27, label: "电影票    ", value: 10083 },
//     { label: '应用', value: 13, label: ' 便捷生活 ', value: 27, label: "天气日历   ", value: 10084 },
//     { label: '应用', value: 13, label: ' 出行导航 ', value: 28, label: "地图     ", value: 10014 },
//     { label: '应用', value: 13, label: ' 出行导航 ', value: 28, label: "导航     ", value: 10015 },
//     { label: '应用', value: 13, label: ' 出行导航 ', value: 28, label: "交通票务   ", value: 10016 },
//     { label: '应用', value: 13, label: ' 出行导航 ', value: 28, label: "用车     ", value: 10017 },
//     { label: '应用', value: 13, label: ' 出行导航 ', value: 28, label: "公交地铁   ", value: 10018 },
//     { label: '应用', value: 13, label: ' 主题个性 ', value: 29, label: "铃声     ", value: 10001 },
//     { label: '应用', value: 13, label: ' 主题个性 ', value: 29, label: "锁屏     ", value: 10002 },
//     { label: '应用', value: 13, label: ' 主题个性 ', value: 29, label: "壁纸     ", value: 10003 },
//     { label: '应用', value: 13, label: ' 主题个性 ', value: 29, label: "桌面     ", value: 10004 },
//     { label: '应用', value: 13, label: ' 教育   ', value: 30, label: "学习     ", value: 10095 },
//     { label: '应用', value: 13, label: ' 教育   ', value: 30, label: "英文     ", value: 10096 },
//     { label: '应用', value: 13, label: ' 教育   ', value: 30, label: "翻译     ", value: 10097 },
//     { label: '应用', value: 13, label: ' 教育   ', value: 30, label: "备考     ", value: 10098 },
//     { label: '应用', value: 13, label: ' 运动健康 ', value: 31, label: "健康     ", value: 10005 },
//     { label: '应用', value: 13, label: ' 运动健康 ', value: 31, label: "养生     ", value: 10006 },
//     { label: '应用', value: 13, label: ' 运动健康 ', value: 31, label: "运动     ", value: 10007 },
//     { label: '应用', value: 13, label: ' 运动健康 ', value: 31, label: "医疗     ", value: 10013 },
//     { label: '应用', value: 13, label: ' 拍摄美化 ', value: 33, label: "拍照     ", value: 10025 },
//     { label: '应用', value: 13, label: ' 拍摄美化 ', value: 33, label: "短视频    ", value: 10026 },
//     { label: '应用', value: 13, label: ' 拍摄美化 ', value: 33, label: "图像美化   ", value: 10027 },
//     { label: '应用', value: 13, label: ' 拍摄美化 ', value: 33, label: "影音编辑   ", value: 10028 },
//     { label: '应用', value: 13, label: ' 拍摄美化 ', value: 33, label: "相册图库   ", value: 10029 },
//     { label: '应用', value: 13, label: ' 新闻阅读 ', value: 345, label: "电子书    ", value: 10085 },
//     { label: '应用', value: 13, label: ' 新闻阅读 ', value: 345, label: "新闻     ", value: 10086 },
//     { label: '应用', value: 13, label: ' 新闻阅读 ', value: 345, label: "动漫     ", value: 10087 },
//     { label: '应用', value: 13, label: ' 新闻阅读 ', value: 345, label: "有声读物   ", value: 10088 },
//     { label: '应用', value: 13, label: ' 新闻阅读 ', value: 345, label: "杂志     ", value: 10089 },
//     { label: '应用', value: 13, label: ' 新闻阅读 ', value: 345, label: "幽默     ", value: 10090 },
//     { label: '应用', value: 13, label: ' 新闻阅读 ', value: 345, label: "体育     ", value: 10091 },
//     { label: '应用', value: 13, label: ' 新闻阅读 ', value: 345, label: "分类信息   ", value: 10501 },
//     { label: '应用', value: 13, label: ' 购物比价 ', value: 358, label: "商城     ", value: 10030 },
//     { label: '应用', value: 13, label: ' 购物比价 ', value: 358, label: "导购     ", value: 10116 },
//     { label: '应用', value: 13, label: ' 购物比价 ', value: 358, label: "团购     ", value: 10031 },
//     { label: '应用', value: 13, label: ' 购物比价 ', value: 358, label: "海淘     ", value: 10032 },
//     { label: '应用', value: 13, label: ' 购物比价 ', value: 358, label: "快递     ", value: 10117 },
//     { label: '应用', value: 13, label: ' 购物比价 ', value: 358, label: "优惠     ", value: 10033 },
//     { label: '应用', value: 13, label: ' 美食   ', value: 359, label: "菜谱     ", value: 10075 },
//     { label: '应用', value: 13, label: ' 美食   ', value: 359, label: "外卖     ", value: 10076 },
//     { label: '应用', value: 13, label: ' 美食   ', value: 359, label: "餐饮     ", value: 10077 },
//     { label: '应用', value: 13, label: ' 美食   ', value: 359, label: "生鲜     ", value: 10078 },
//     { label: '应用', value: 13, label: ' 汽车   ', value: 360, label: "养车     ", value: 10099 },
//     { label: '应用', value: 13, label: ' 汽车   ', value: 360, label: "违章查询   ", value: 10100 },
//     { label: '应用', value: 13, label: ' 汽车   ', value: 360, label: "汽车资讯   ", value: 10101 },
//     { label: '应用', value: 13, label: ' 汽车   ', value: 360, label: "驾考     ", value: 10102 },
//     { label: '应用', value: 13, label: ' 旅游住宿 ', value: 361, label: "旅游     ", value: 10072 },
//     { label: '应用', value: 13, label: ' 旅游住宿 ', value: 361, label: "住宿     ", value: 10073 },
//     { label: '应用', value: 13, label: ' 旅游住宿 ', value: 361, label: "行程助手   ", value: 10074 },
//     { label: '应用', value: 13, label: ' 商务   ', value: 362, label: "办公软件   ", value: 10103 },
//     { label: '应用', value: 13, label: ' 商务   ', value: 362, label: "效率     ", value: 10104 },
//     { label: '应用', value: 13, label: ' 商务   ', value: 362, label: "笔记     ", value: 10105 },
//     { label: '应用', value: 13, label: ' 商务   ', value: 362, label: "邮箱     ", value: 10106 },
//     { label: '应用', value: 13, label: ' 商务   ', value: 362, label: "招聘     ", value: 10107 },
//     { label: '应用', value: 13, label: ' 儿童   ', value: 363, label: "儿童教育   ", value: 10092 },
//     { label: '应用', value: 13, label: ' 儿童   ', value: 363, label: "儿歌     ", value: 10093 },
//     { label: '应用', value: 13, label: ' 儿童   ', value: 363, label: "母婴     ", value: 10094 }]


// function group(arr) {
//     let left = []
//     let right = []



//     return [{
//         value: 2,
//         label: '游戏',
//         children: left
//     },
//     {
//         value: 2,
//         label: '游戏',
//         children: right
//     }]
// }